### ISSUE TITLE
Predictive Text Disabled Causes Crash

### ISSUE THREAD

**Issue by Hydroxing** [MTACS/DopeConvos#27] opened 2020-04-28 12:38 UTC
**Describe the bug**
Messages.app crashes when Predictive Text is disabled in Settings and iOS attempts to autocorrect something typed in any message field in Messages.app

**To Reproduce**
1) Mistype any word in the message field of a conversation OR mistype a user-generated shortcut
2) Have iOS prompt to automatically correct it with the suggested word iOS believes is correct
3) Crash

**Expected behavior**
The Messages.app should not crash.

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone Xs Max]
 - iOS Version: [13.3]
 - Package Manager: [Cydia]
 - Tweak Version: [1.9]

**Additional context**
No other tweaks are injecting into messages.app

**Comment by nahtedetihw** [comment] 2020-05-11 04:30
Does this issue still persist in the latest version?

**Comment by Hydroxing** [comment] 2020-05-11 06:03
Hi,

Yes, it still does unfortunately. Have had to disable DopeConvos with iCleaner for the time being.

**Comment by Hydroxing** [comment] 2020-05-19 15:57
This is still occurring in 2.5. No other tweaks are being loaded into messages too so it is definitely DopeConvos causing the crash.

**Comment by nahtedetihw** [comment] 2020-05-19 17:32
The issue is caused by Predictive bar being turned off in Settings>General>Keyboard. I believe this is caused by NudeKeys. Do you have that tweak installed and that option disabled?

**Comment by Hydroxing** [comment] 2020-05-19 17:34
I do not have NudeKeys installed anymore. I did at one point though. Predictive is turned off but would like to keep it off too. If I have to turn it off for the time being, I will.

**Comment by nahtedetihw** [comment] 2020-05-19 17:37
Possibly there are leftover NudeKeys files, check /private/var/mobile/Library/Preferences for NudeKeys plist and delete it, that should fix the crash and allow you to have Predictive Bar disabled still

**Comment by Hydroxing** [comment] 2020-05-19 17:38
Thank you Ethan, will try this.

**Comment by Hydroxing** [comment] 2020-05-19 17:46
So deleting those files did nothing and Predictive off is definitely the culprit. Right now, only able to use tweak with Predictive on.

**Comment by nahtedetihw** [comment] 2020-05-19 20:39
Fixed in version 2.6

**Comment by Hydroxing** [comment] 2020-05-19 20:45
Sweet! Thank you so much for looking into this! Any ETA on when 2.6 gets a public release?

**Comment by nahtedetihw** [comment] 2020-05-19 20:46
Twickd usually pushes my updates pretty fast, I would say within the next couple hours

**Comment by Hydroxing** [comment] 2020-05-19 20:50
Awesome! You're a great Dev for doing _actual_ support and being responsive/responsible for bugs in your software.

**Comment by nahtedetihw** [comment] 2020-05-19 22:17
Thanks I appreciate that. Let me know if you experience any issues with the new update or if you have any more bugs pop up. I keep this bug report open until you have a chance to test out the fix.

**Closed** 2020-05-25 03:24 UTC
Labels: bug
